# Generated by Django 5.0.6 on 2026-08-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Practice Staff'), ('doctor', 'Doctor'), ('referrer', 'Referring Provider')], default='referrer', max_length=20),
        ),
    ]
