# Generated by Django 5.0.6 on 2026-07-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('kind', models.CharField(choices=[('lecture', 'Lecture / Course'), ('event', 'Event'), ('webinar', 'Webinar')], max_length=20)),
                ('audience', models.CharField(blank=True, help_text='e.g. Doctors, Allied HC professionals, Public', max_length=200)),
                ('starts_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('fee', models.CharField(blank=True, max_length=100)),
                ('registration_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('kind', models.CharField(choices=[('article', 'Journal article'), ('book_chapter', 'Book chapter'), ('book', 'Book'), ('patent', 'Patent')], max_length=20)),
                ('authors', models.CharField(blank=True, max_length=300)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-year', 'order'],
            },
        ),
    ]
