# Generated by Django 5.0.6 on 2026-07-25 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('patient_testimonial', 'Patient testimonial'), ('educational', 'Educational'), ('office_tour', 'Office tour')], default='patient_testimonial', max_length=30)),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo/hosted URL (leave blank if uploading a file instead)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/')),
                ('caption_text', models.TextField(blank=True, help_text='Subtitle/transcript text shown with the video.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('page', models.ForeignKey(blank=True, help_text='Optionally assign this video to a specific page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='pages.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
