# Generated by Django 5.0.6 on 2026-07-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('epworth', 'Epworth Sleepiness Scale'), ('stop_bang', 'STOP-BANG Questionnaire'), ('tmj_pain_scale', 'TMJ Pain Scale'), ('cgasp', 'C-GASP Screener'), ('cpap_intolerance', 'CPAP Intolerance Affidavit'), ('referral', 'Referral Form')], max_length=30)),
                ('patient_name', models.CharField(blank=True, max_length=200)),
                ('submitted_by_name', models.CharField(blank=True, help_text='Referring doctor, if this is a referral', max_length=200)),
                ('answers', models.JSONField(default=dict)),
                ('computed_score', models.CharField(blank=True, help_text="e.g. 'Epworth: 14/24' or 'STOP-BANG: 5 (High Risk)'", max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('office_reviewed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
