# Generated by Django 5.0.6 on 2026-07-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role_title', models.CharField(blank=True, max_length=150)),
                ('credentials', models.CharField(blank=True, help_text='e.g. DMD, C.DSM', max_length=100)),
                ('specialty', models.CharField(blank=True, help_text='e.g. Orthodontist, TMJ & Sleep Medicine', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('education', models.TextField(blank=True, help_text='One item per line')),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('is_doctor', models.BooleanField(default=False)),
                ('accepting_new_patients', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
