# Generated by Django 5.0.6 on 2026-07-25 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('reason_for_visit', models.CharField(choices=[('orthodontic', 'Orthodontic / Braces evaluation'), ('tmj', 'TMJ / Jaw pain'), ('sleep_airway', 'Sleep / Airway / Snoring'), ('second_opinion', 'Second opinion'), ('other', 'Other')], max_length=30)),
                ('is_new_patient', models.BooleanField(default=True)),
                ('referred_by', models.CharField(blank=True, max_length=200)),
                ('has_sleep_study', models.BooleanField(default=False)),
                ('sleep_study_file', models.FileField(blank=True, null=True, upload_to='patient_uploads/sleep_studies/')),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('office_reviewed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Treatment completed')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='team.teammember')),
                ('source_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_record', to='patients.patientformsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
