# Generated by Django 5.0.6 on 2026-07-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='service',
            field=models.CharField(blank=True, choices=[('early_ortho_4_6', 'Early Orthodontics, Ages 4-6'), ('ortho_7_11', 'Orthodontics, Ages 7-11'), ('teen_ortho', 'Teen Orthodontics'), ('adult_ortho', 'Adult Orthodontics'), ('tmj', 'TMJ Disorders'), ('sleep_airway', 'Sleep, Breathing & Airway Disorders'), ('myofunctional', 'Myofunctional Therapy'), ('airway_diagnostics', 'Airway Diagnostics')], max_length=50, null=True),
        ),
    ]
