# Generated by Django 5.0.6 on 2026-07-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('treatment', models.CharField(blank=True, max_length=200)),
                ('before_image', models.ImageField(upload_to='patient_gallery/before/')),
                ('after_image', models.ImageField(upload_to='patient_gallery/after/')),
                ('patient_age', models.CharField(blank=True, max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
