# Generated by Django 5.0.6 on 2026-07-25 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Nav categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.CharField(blank=True, help_text='Used in nav tooltips / SEO description', max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/hero/')),
                ('show_in_nav', models.BooleanField(default=True)),
                ('nav_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nav_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='pages.navcategory')),
            ],
            options={
                'ordering': ['nav_category__order', 'nav_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DownloadableForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='forms/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='pages.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rich_text', 'Rich text'), ('image', 'Image with caption'), ('video_embed', 'Embedded video'), ('form_links', 'Downloadable forms list'), ('stat_callout', 'Highlighted stat / quote'), ('cta', 'Call to action')], default='rich_text', max_length=20)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/sections/')),
                ('video_url', models.URLField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
