# Generated by Django 5.0.6 on 2026-07-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cherry', 'Cherry'), ('credit_cards', 'Credit Cards'), ('hsa', 'Health Savings Accounts (HSA)'), ('health_financing_direct', 'Health Financing Direct'), ('carecredit', 'CareCredit')], max_length=40, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='financing/')),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('learn_more_url', models.URLField(blank=True)),
                ('widget_script_url', models.URLField(blank=True, help_text='Cherry Widget Builder output URL (full-page + floating button).')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
