# Generated by Django 5.0.6 on 2026-07-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150)),
                ('source', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('website', 'Submitted on website'), ('other', 'Other')], default='website', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('body', models.TextField()),
                ('review_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False, help_text='Reviews submitted on the site require staff approval before they show publicly.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-review_date'],
            },
        ),
    ]
